# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5da8ce94cb30333acbe7683896d9163ebbca0d874fccf5c3bf17cdc9859333faff3b9f16365771a9e26d266fdaeb935548c489eab0dece08766fe07c8de8564

test:
  secret_key_base: 91bf392e2f5c3decb62b0758eaf767d43154b3a3888353edbbbf072710961096bf6a680f14c367e09b1ce00896bc4093b36dfc94e72fa0ed1ab32104be3efafe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
